### ISSUE TITLE
SP3: Keyboard backlight stays on when suspending

### ISSUE THREAD

**Issue by Larx** [jakeday/linux-surface#453]
On my Surface Pro 3 with latest kernel from here, keyboard backlight stays on when suspending. Or rather, it keeps the state it has when suspending, which means that especially a manual suspend has this problem. Suspend after inactivity is unproblematic, as keyboard backlight tends to be off then ;-). Hibernate does not have this problem.

**Comment by jonas2515** [comment]
See https://github.com/qzed/linux-surfacegen5-acpi/issues/4, I guess this also works for the sp3.

**Comment by qzed** [comment]
Do you know which HID devices are affected by this? I'd assume
```
USB_DEVICE_ID_MS_TYPE_COVER_PRO_3	0x07dc
USB_DEVICE_ID_MS_TYPE_COVER_PRO_3_1	0x07de
USB_DEVICE_ID_MS_TYPE_COVER_PRO_3_2	0x07e2
USB_DEVICE_ID_MS_TYPE_COVER_PRO_3_JP	0x07dd
USB_DEVICE_ID_MS_TYPE_COVER_PRO_4	0x07e8
USB_DEVICE_ID_MS_TYPE_COVER_PRO_4_1	0x07e4
```
Can you check that your device IDs are included there?

Also I'll keep the issue on the linux-surfacegen5-acpi repo open for now (due to the discussion in it), but I think this should be directly included as a patch in this repo here. I should have some time at the weekend to make a PR, if you don't have a patch already.

**Comment by qzed** [comment]
@Larx Before we do something wrong, can you verify that the script provided by @jonas2515 in https://github.com/qzed/linux-surfacegen5-acpi/issues/4#issuecomment-473236117 also toggles the backl-ight for the SP3, I'd assume it should work, but it's better we make sure before implementing this. Note that you need to change the `idProduct` to your ID.

**Comment by Larx** [comment]
I'll try, will take a few days, however, until I'll find the time.

**Comment by Larx** [comment]
Unfortunately, the script seems not to work for me. I use the ID 045e:07dc (as this disappears when I disattach the keyboard, it should be the right device).

`Traceback (most recent call last):
  File "backlight.py", line 27, in <module>
    dev.ctrl_transfer(0x21, 0x09, 0x0324, 0, [0x24, 0xFF, 0x00, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00])
  File "/usr/lib/python2.7/dist-packages/usb/core.py", line 1043, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/usr/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 883, in ctrl_transfer
    timeout))
  File "/usr/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 32] Pipe error
`

**Comment by Larx** [comment]
PS. Same error with Python3.

**Comment by jonas2515** [comment]
That sounds like the request timed out, so maybe your keyboard needs another command to toggle the backlight. Can you try installing USBlyzer on Windows and share the logs of a suspend+resume cycle? Try not to use the keyboard during that cycle, that will make the logs a lot noisier. Turn the device on and off using the power button and start/stop logging with the touchscreen.

**Comment by Larx** [comment]
Sorry, Windows is not available on this device.
